name: workflow with artifacts

on: [push]

env:
  ARTIFACT_NAME: myartifact
  
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
        - name: Check out the code
          uses: actions/checkout@v4
        - name: Build ${{ env.ARTIFACT_NAME }} for ubuntu-latest
          run: go build ${{ env.ARTIFACT_NAME }}.go          
        - name: Upload the artifact
          uses: actions/upload-artifact@v4
          with:
            name: linux
            path: ./${{ env.ARTIFACT_NAME }}
